---
name: concurrency_limit_ci_archive_trace_worker
description:
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/196373
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/553177
milestone: '18.2'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
