---
name: packages_protected_packages_nuget
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/323972
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/184059
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/524145
milestone: '18.0'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
